### ISSUE TITLE
[libfuse version] This is not really an issue but rather a question.

### ISSUE THREAD

**Issue by rhighs** [idkr-client/idkr#31]
Why does the latest app image x86_64 1.2.2 works fine with libfuse2 but refuses to run with libfuse3?

**Comment by Mixaz017** [comment]
I know this is a year old question but here I am.
Apparently this is AppImage thing, AppImage requires FUSE 2 to run.
https://docs.appimage.org/user-guide/troubleshooting/fuse.html
