### ISSUE TITLE
Problem on MacOS

### ISSUE THREAD

**Issue by Kiyoshi-23** [idkr-client/idkr#47]
Opens and then just shows a blank white screen as shown here
![Screen Shot 2021-09-29 at 6 15 52 PM](https://user-images.githubusercontent.com/90008981/135361444-118c2bf3-bf10-4bd1-b77e-8ee97ffc1190.png)
.

**Comment by moonyaim** [comment]
Is there a log file on the system? I'm nit really sure about the MacOS release of idkr
