### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by bubblubububbulblubub** [idkr-client/idkr#58]
hello I've never used github before so I'm hoping this is the right place, but occasionally the client will randomly use all of my ram in the background to the point where it takes a full minute to open task manager to close it. the only thing i can think of that might cause it is me having my sample rate as 96k in windows because its only recently I've been having this problem and i used to use 44.1k. i don't know if this is important or not but i wanted to report it

**Comment by Mixaz017** [comment]
Does it only occur in idkr? And how long it usually takes to happen?

**Comment by Mixaz017** [comment]
and also, more information about your RAM would be helpful

**Comment by Mixaz017** [comment]
So you keep idkr open for 3 days without closing? Or, when you close idkr, a process is left open taking a lot of RAM?

**Comment by bubblubububbulblubub** [comment]
when i close idkr

**Comment by bubblubububbulblubub** [comment]
apologies if that was a lot of information i wanted to be in-depth

**Comment by SolarSun13** [comment]
Re-installed today and experienced the same issue upon first install and final close (reopened a few times). Program had been closed and resulted in taking up 94% memory usage after noticing ~1hour later. 32gb ram ~3000mhz as well.

**Comment by Mixaz017** [comment]
Thats a serious problem. As I cant replicate the issue, can you test which part of idkr is causing the issue? You can disable certain features (Discord RPC, Swapper, etc) and see if the memory usage still go crazy.

**Comment by SolarSun13** [comment]
Played today and haven't noticed the same issue. Tried opening and closing many times as well. Yesterday was a fresh re-install after some time (Discord RPC has always been on, and swapper folders were retained from last install still active). Not sure if either of these two things matter at all, but figured I'd mention - the app was launched via the auto created shortcut on the desktop yesterday but not today, as well as is installed on a D drive external from the main Operating System C drive (both this installation and prior).

I'll try to report here once again if I noticed the same or similar issues, may have just needed an initial compute restart. 👍

**Comment by Mixaz017** [comment]
Thank you for more info. I don't think the way you launch idkr or the install location matter.
Also, how long did it take for you to notice the memory leak after closing the client?

**Comment by SolarSun13** [comment]
About an hour give or take, I wasn't doing too much else but only noticed after launching another game program.

**Comment by Hiro527** [comment]
I've heard that it'd occured in LaF client some times.
Electron was using about 8GB ram after closing the app.
I guess it might be bug of electron 9.4.x and if so, it won't be resolved cuz it's no longer supported ;(

**Comment by bubblubububbulblubub** [comment]
the latest update fixed it for me thank you
